sudo: false
branches:
  only:
    - master
language: python
python:
  - 3.6
before_install:
  - pip install --upgrade pip
  - pip --version
  - pip install --upgrade flake8
  - flake8 . --count --statistics
install: python build.py dev
script:
  - flake8 . --count --max-line-length=127 --select=E999  # Stop the build on syntax errors
  - python build.py test_cov
notifications:
  email: false
  irc: 
    channels:
      - "irc.freenode.org#aspen"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
